### ISSUE TITLE
How to catch ConfigurationProfileException?

### ISSUE THREAD

**Issue by JakobMiksch** [empatica/empalink-sample-project-android#17]
The sample app crashed with a wrong credentials and produces a  `ConfigurationProfileException` . I tried to catch it like this:

```
try {
    // Initialize the Device Manager using your API key. You need to have Internet access at this point.
    deviceManager.authenticateWithAPIKey(EMPATICA_API_KEY);
} catch (ConfigurationProfileException e) {
    Log.e(TAG, "Error with API Key", e);
}
```
But it does not work. 

How can a wrongly entered API be catched?

**Comment by troeggla** [comment]
I've ran into the same problem and indeed it seems like that this exception cannot be caught (at least not with a `try`/`catch` block). However, after some trial and error, I found kind of a solution. It is certainly not optimal, but it seems to be the only way to achieve this with the library in its current state.

The solution is to implement the `Thread.UncaughtExceptionHandler` interface in your app and install it in your activity. I've created a separate class for it:

```java
public class ConfigurationProfileExceptionHandler implements Thread.UncaughtExceptionHandler {
    private static final String TAG = "ConfigurationProfileExceptionHandler";
    private static final String API_KEY_INVALID = "API_KEY_INVALID";

    private Context context;
    private Class<?> nextActivity;

    public ConfigurationProfileExceptionHandler(Context context, Class<?> nextActivity) {
        this.context = context;
        this.nextActivity = nextActivity;
    }

    @Override
    public void uncaughtException(Thread thread, Throwable ex) {
        Log.e(TAG, "uncaughtException: " + ex);

        // Check if exception is of type ConfigurationProfileException
        if (ex instanceof ConfigurationProfileException) {
            // Set API_KEY_INVALID flag and restart activity
            Intent restart = new Intent(context, nextActivity);
            restart.putExtra(API_KEY_INVALID, true);

            context.startActivity(restart);
        }

        // Kill app and exit in any case
        Process.killProcess(Process.myPid());
        System.exit(0);
    }
}
```

Then, install this exception handler in the `onCreate()` method of your activity like so:

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    Thread.setDefaultUncaughtExceptionHandler(new ConfigurationProfileExceptionHandler(this, MainActivity.class));

    // If API_KEY_INVALID flag is set, the app was restarted due to a ConfigurationProfileException
    boolean apiKeyInvalid = getIntent().getBooleanExtra(API_KEY_INVALID, false);

    [...]
}
```

The drawback of this solution is that once the `uncaughtException()` method is invoked, your app has already sort of crashed, i.e. you cannot show any dialogues or error messages. Your best bet is simply to restart the activity. That's why I pass the `API_KEY_INVALID` flag along so I know whether the app was restarted due to a `ConfigurationProfileException`.

I hope this workaround helps anyone until this issue is addressed properly.
